services:
  - type: web
    name: dtf-customizer-backend
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python render_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000
